### PR TITLE
V1.7 s2

### PR DESCRIPTION
**Pull request by marklangerhacker**
Add compyability to addons

### CODE REVIEW

**Comment by SoulxluoS** [comment]
What's the problem with them?

**Comment by marklangerhacker** [comment]
Spiders are brocken, some mobs doesn't have additional part, piglin's animation are laggy, some of mobs doesn't have random textures(maybe)

**Comment by marklangerhacker** [comment]
> What's the problem with them?

Spiders are brocken, some mobs doesn't have additional part, piglin's animation are laggy, some of mobs doesn't have random textures(maybe)
It's about main official addon

**Comment by SoulxluoS** [comment]
Piglings - yes, work on it. 
Addition part need test.
For random texture need other mod- entity texture feature.

**Comment by SoulxluoS** [comment]
For eyes blinking need mods Animatica https://modrinth.com/mod/animatica

**Pull request closed without merging**
